USE [master]
GO

/****** Object:  Database [ProvaHigorCouto]    Script Date: 13/10/2019 19:58:34 ******/
CREATE DATABASE [ProvaHigorCouto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProvaHigorCouto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ProvaHigorCouto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProvaHigorCouto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ProvaHigorCouto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProvaHigorCouto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProvaHigorCouto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProvaHigorCouto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProvaHigorCouto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProvaHigorCouto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProvaHigorCouto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET RECOVERY FULL 
GO

ALTER DATABASE [ProvaHigorCouto] SET  MULTI_USER 
GO

ALTER DATABASE [ProvaHigorCouto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProvaHigorCouto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProvaHigorCouto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProvaHigorCouto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProvaHigorCouto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProvaHigorCouto] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProvaHigorCouto] SET  READ_WRITE 
GO


